#!/bin/bash
set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
cp -Rf /tmp/src/* /var/www/html/


# Fix source directory permissions
#fix-permissions /var/www/html /var/run/httpd /var/log/httpd

echo
echo "===> Build completed at $(date)"
